const psdData: {
  id: string;
  image: string;
  image_webp?: string;
  width: number;
  height: number;
  colorMode: number;
  layers: any[];
}[] = [
  {
    id: "4",
    image:
      "https://localhost:3001/images/image-fc9b3319289ce329ec1a91780d7da977.png",
    image_webp:
      "https://localhost:3001/images/image-fc9b3319289ce329ec1a91780d7da977.webp",
    width: 1080,
    height: 1920,
    colorMode: 3,
    layers: [
      {
        type: "image",
        id: "image_2",
        clipping: false,
        name: "背景1",
        y: 0,
        x: 0,
        width: 1080,
        height: 1920,
        image:
          "https://localhost:3001/images/image-6c19533d67d1905ee697083a13a2bc6b.png",
        image_webp:
          "https://localhost:3001/images/image-6c19533d67d1905ee697083a13a2bc6b.webp",
        zIndex: 0,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_3",
        clipping: false,
        name: "其他",
        y: 137,
        x: 103,
        width: 874,
        height: 1155,
        image:
          "https://localhost:3001/images/image-939294b6fbc0e130a948cc73f30905ef.png",
        image_webp:
          "https://localhost:3001/images/image-939294b6fbc0e130a948cc73f30905ef.webp",
        zIndex: 1,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_5",
        clipping: false,
        name: "商品1-截图",
        y: 152,
        x: 117,
        width: 845,
        height: 1125,
        image:
          "https://localhost:3001/images/image-5a2dd5255fad286aceaea835815b46ae.png",
        image_webp:
          "https://localhost:3001/images/image-5a2dd5255fad286aceaea835815b46ae.webp",
        zIndex: 2,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_24",
        clipping: false,
        name: "其他",
        y: 1215,
        x: 134,
        width: 124,
        height: 123,
        image:
          "https://localhost:3001/images/image-7538876dd18dd552230146060b6ca5f7.png",
        image_webp:
          "https://localhost:3001/images/image-7538876dd18dd552230146060b6ca5f7.webp",
        zIndex: 3,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_38",
        clipping: false,
        name: "其他",
        y: 1349,
        x: 0,
        width: 1080,
        height: 571,
        image:
          "https://localhost:3001/images/image-28f2ef06c0b42ef7190c7c18e39ba214.png",
        image_webp:
          "https://localhost:3001/images/image-28f2ef06c0b42ef7190c7c18e39ba214.webp",
        zIndex: 4,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_26",
        clipping: false,
        name: "贴纸-免邮-其他",
        y: 102,
        x: 618,
        width: 379,
        height: 99,
        image:
          "https://localhost:3001/images/image-fc2224443d6684f943aa11c614cde658.png",
        image_webp:
          "https://localhost:3001/images/image-fc2224443d6684f943aa11c614cde658.webp",
        zIndex: 5,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_27",
        name: "贴纸-免邮-文案",
        x: 656,
        y: 136,
        width: 302,
        height: 30,
        text: "FREE SHIPPING",
        fontFamily: "TitanOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 39.7,
        fill: "rgba(255,255,255,1)",
        align: "right",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 6,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_28",
        name: "文案2",
        x: 103,
        y: 1633,
        width: 872,
        height: 167,
        text: "SHOW OFF\nYOUR UNIQUE STYLE",
        fontFamily: "TitanOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 83.5,
        fill: "rgba(255,228,185,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 2,
        lineHeight: 1.14,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 7,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_30",
        clipping: false,
        name: "其他",
        y: 1215,
        x: 593,
        width: 404,
        height: 408,
        image:
          "https://localhost:3001/images/image-5c7d805a4aa6e3a527623db8d1ba8ab4.png",
        image_webp:
          "https://localhost:3001/images/image-5c7d805a4aa6e3a527623db8d1ba8ab4.webp",
        zIndex: 8,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_33",
        clipping: false,
        name: "贴纸-用户专享",
        y: 1530,
        x: 103,
        width: 403,
        height: 51,
        image:
          "https://localhost:3001/images/image-6e43a5406941124d49a12fea6228afb5.png",
        image_webp:
          "https://localhost:3001/images/image-6e43a5406941124d49a12fea6228afb5.webp",
        zIndex: 9,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_34",
        name: "文案1",
        x: 639,
        y: 1339,
        width: 312,
        height: 128,
        text: "UP TO\n90% OFF",
        fontFamily: "TitanOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 70.11,
        fill: "rgba(255,255,255,1)",
        align: "center",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 2,
        lineHeight: 1.08,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 10,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_35",
        name: "CTA",
        x: 110,
        y: 1466,
        width: 220,
        height: 25,
        text: "SHOP NOW",
        fontFamily: "Lato-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 35.44,
        fill: "rgba(255,255,255,1)",
        align: "center",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 4,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 11,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
    ],
  },
  {
    id: "5",
    image:
      "https://localhost:3001/images/image-f21fbcd7635490d5b61a9366abdb73b5.png",
    image_webp:
      "https://localhost:3001/images/image-f21fbcd7635490d5b61a9366abdb73b5.webp",
    width: 1080,
    height: 1920,
    colorMode: 3,
    layers: [
      {
        type: "image",
        id: "image_66",
        clipping: false,
        name: "背景1",
        y: 0,
        x: 0,
        width: 1080,
        height: 1920,
        image:
          "https://localhost:3001/images/image-4a9afd14d0c7a09de7ad426b13b07c13.png",
        image_webp:
          "https://localhost:3001/images/image-4a9afd14d0c7a09de7ad426b13b07c13.webp",
        zIndex: 0,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_35",
        clipping: false,
        name: "商品1-截图",
        y: 104,
        x: 114,
        width: 852,
        height: 1287,
        image:
          "https://localhost:3001/images/image-4ea522451655783d548dd8cfb631af05.png",
        image_webp:
          "https://localhost:3001/images/image-4ea522451655783d548dd8cfb631af05.webp",
        zIndex: 1,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_10",
        clipping: false,
        name: "其他",
        y: -145,
        x: -62,
        width: 1142,
        height: 2065,
        image:
          "https://localhost:3001/images/image-82f27b541801fcb79d77062b2875dba1.png",
        image_webp:
          "https://localhost:3001/images/image-82f27b541801fcb79d77062b2875dba1.webp",
        zIndex: 2,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_14",
        clipping: false,
        name: "其他",
        y: 1340,
        x: 478,
        width: 602,
        height: 472,
        image:
          "https://localhost:3001/images/image-d007d7083ee7694ed356cb6fa643085f.png",
        image_webp:
          "https://localhost:3001/images/image-d007d7083ee7694ed356cb6fa643085f.webp",
        zIndex: 3,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_16",
        clipping: false,
        name: "其他",
        y: 1392,
        x: 890,
        width: 80,
        height: 9,
        image:
          "https://localhost:3001/images/image-00710d9255f193ab90c3871d3576927f.png",
        image_webp:
          "https://localhost:3001/images/image-00710d9255f193ab90c3871d3576927f.webp",
        zIndex: 4,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_17",
        name: "CTA",
        x: 114,
        y: 1758,
        width: 278,
        height: 33,
        text: "SHOP NOW",
        fontFamily: "Lato-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 44.73,
        fill: "rgba(255,255,255,1)",
        align: "center",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 4,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 5,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_18",
        name: "文案2",
        x: 520,
        y: 1693,
        width: 382,
        height: 68,
        text: "SHOW OFF\nYOUR UNIQUE STYLE",
        fontFamily: "Lato-Black",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 34.99,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 2,
        lineHeight: 1.06,
        letterSpacing: 1,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 6,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_19",
        name: "文案1",
        x: 521,
        y: 1457,
        width: 449,
        height: 196,
        text: "UP TO\n90% OFF",
        fontFamily: "Lato-Black",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 112.07,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 2,
        lineHeight: 0.99,
        letterSpacing: -2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 7,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_15",
        name: "贴纸-免邮-文案",
        x: 604,
        y: 1385,
        width: 246,
        height: 25,
        text: "FREE SHIPPING",
        fontFamily: "NotoSansTC-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 43.07,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [0.79, 0, 0, 0.79, 0, 0],
        lineNumber: 1,
        lineHeight: 0.68,
        letterSpacing: 1,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 8,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_34",
        clipping: false,
        name: "贴纸-免邮-其他",
        y: 1378,
        x: 514,
        width: 72,
        height: 42,
        image:
          "https://localhost:3001/images/image-a317adc0cf208ebc7f83ef104811ec45.png",
        image_webp:
          "https://localhost:3001/images/image-a317adc0cf208ebc7f83ef104811ec45.webp",
        zIndex: 9,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_27",
        clipping: false,
        name: "贴纸-用户专享",
        y: 1442,
        x: 135,
        width: 235,
        height: 235,
        image:
          "https://localhost:3001/images/image-c1e219f885779ca0bf6b64f9bb3c4ba7.png",
        image_webp:
          "https://localhost:3001/images/image-c1e219f885779ca0bf6b64f9bb3c4ba7.webp",
        zIndex: 10,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
    ],
  },
  {
    id: "2",
    image:
      "https://localhost:3001/images/image-2c25762a34213818828e248f79b5ff4e.png",
    image_webp:
      "https://localhost:3001/images/image-2c25762a34213818828e248f79b5ff4e.webp",
    width: 1080,
    height: 1920,
    colorMode: 3,
    layers: [
      {
        type: "image",
        id: "image_2",
        clipping: false,
        name: "背景1",
        y: 0,
        x: 0,
        width: 1080,
        height: 1920,
        image:
          "https://localhost:3001/images/image-049a5164b9ca450e41369f6cd6a35906.png",
        image_webp:
          "https://localhost:3001/images/image-049a5164b9ca450e41369f6cd6a35906.webp",
        zIndex: 0,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_3",
        clipping: false,
        name: "商品1-抠图",
        y: 301,
        x: 57,
        width: 947,
        height: 1328,
        image:
          "https://localhost:3001/images/image-d7f8338ca88cc6e7e00e87a5018affc1.png",
        image_webp:
          "https://localhost:3001/images/image-d7f8338ca88cc6e7e00e87a5018affc1.webp",
        zIndex: 1,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_4",
        clipping: false,
        name: "其他",
        y: 1462,
        x: 0,
        width: 1080,
        height: 458,
        image:
          "https://localhost:3001/images/image-51c69879fabd598c245d2a02244dcff1.png",
        image_webp:
          "https://localhost:3001/images/image-51c69879fabd598c245d2a02244dcff1.webp",
        zIndex: 2,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_5",
        clipping: false,
        name: "其他",
        y: 274,
        x: 102,
        width: 140,
        height: 13,
        image:
          "https://localhost:3001/images/image-a6501ca1f9e20df81eda4512a5a406f7.png",
        image_webp:
          "https://localhost:3001/images/image-a6501ca1f9e20df81eda4512a5a406f7.webp",
        zIndex: 3,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_6",
        name: "CTA",
        x: 674,
        y: 1756,
        width: 303,
        height: 36,
        text: "SHOP NOW",
        fontFamily: "Lato-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 48.79,
        fill: "rgba(255,255,255,1)",
        align: "center",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 5,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 4,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_7",
        name: "文案1",
        x: 103,
        y: 101,
        width: 670,
        height: 123,
        text: "SHOW OFF\nYOUR UNIQUE STYLE",
        fontFamily: "WorkSans-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 85.93,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [0.73, 0, 0, 0.73, 0, 0],
        lineNumber: 2,
        lineHeight: 1.1,
        letterSpacing: 2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 5,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_8",
        name: "贴纸-价格-其他",
        x: 103,
        y: 1609,
        width: 212,
        height: 39,
        text: "Starting At",
        fontFamily: "WorkSans-SemiBold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 40.4,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 6,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_9",
        name: "贴纸-价格-金额",
        x: 101,
        y: 1668,
        width: 455,
        height: 148,
        text: "$1.00",
        fontFamily: "WorkSans-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 176.61,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 7,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_20",
        name: "贴纸-免邮-文案",
        x: 103,
        y: 515,
        width: 222,
        height: 96,
        text: "FREE\nSHIPPING",
        fontFamily: "NotoSansTC-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 79.5,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [0.6, 0, 0, 0.6, 0, 0],
        lineNumber: 2,
        lineHeight: 1.21,
        letterSpacing: 2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 8,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_11",
        name: "贴纸-用户专享",
        x: 102,
        y: 347,
        width: 216,
        height: 74,
        text: "APP New\nUsers Only",
        fontFamily: "WorkSans-Medium",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 37.62,
        fill: "rgba(226,89,35,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 2,
        lineHeight: 1.07,
        letterSpacing: 2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 9,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
    ],
  },
  {
    id: "8",
    image:
      "https://localhost:3001/images/image-dd4c4281ec53868b7bab39d414a9fa68.png",
    image_webp:
      "https://localhost:3001/images/image-dd4c4281ec53868b7bab39d414a9fa68.webp",
    width: 1080,
    height: 1920,
    colorMode: 3,
    layers: [
      {
        type: "image",
        id: "image_700",
        clipping: false,
        name: "背景1",
        y: 0,
        x: 0,
        width: 1080,
        height: 1920,
        image:
          "https://localhost:3001/images/image-4a9afd14d0c7a09de7ad426b13b07c13.png",
        image_webp:
          "https://localhost:3001/images/image-4a9afd14d0c7a09de7ad426b13b07c13.webp",
        zIndex: 0,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_662",
        clipping: false,
        name: "商品1-截图",
        y: 0,
        x: -23,
        width: 1126,
        height: 1500,
        image:
          "https://localhost:3001/images/image-c6757538957dd10aef8dd5e1eb8b28d9.png",
        image_webp:
          "https://localhost:3001/images/image-c6757538957dd10aef8dd5e1eb8b28d9.webp",
        zIndex: 1,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_643",
        clipping: false,
        name: "其他",
        y: 1446,
        x: 0,
        width: 1080,
        height: 633,
        image:
          "https://localhost:3001/images/image-274983aefbc9feece9dd69682cf5983b.png",
        image_webp:
          "https://localhost:3001/images/image-274983aefbc9feece9dd69682cf5983b.webp",
        zIndex: 2,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_636",
        name: "文案2",
        x: 123,
        y: 1535,
        width: 833,
        height: 76,
        text: "UP TO 90% OFF",
        fontFamily: "WorkSans-ExtraBold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 159.65,
        fill: "rgba(0,0,0,1)",
        align: "center",
        transform: [0.7, 0, 0, 0.7, 0, 0],
        lineNumber: 1,
        lineHeight: 1.06,
        letterSpacing: -3,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 3,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_637",
        name: "文案1",
        x: 187,
        y: 1652,
        width: 706,
        height: 36,
        text: "SHOW OFF YOUR UNIQUE STYLE",
        fontFamily: "WorkSans-SemiBold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 117.72,
        fill: "rgba(255,255,255,1)",
        align: "center",
        transform: [0.36, 0, 0, 0.36, 0, 0],
        lineNumber: 1,
        lineHeight: 0.75,
        letterSpacing: 2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 4,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_639",
        clipping: false,
        name: "贴纸-免邮-其他",
        y: 1418,
        x: 346,
        width: 388,
        height: 59,
        image:
          "https://localhost:3001/images/image-2d203ddd18fd6819e11ea7313bf8f739.png",
        image_webp:
          "https://localhost:3001/images/image-2d203ddd18fd6819e11ea7313bf8f739.webp",
        zIndex: 5,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_640",
        name: "贴纸-免邮-文案",
        x: 371,
        y: 1430,
        width: 339,
        height: 36,
        text: "FREE SHIPPING",
        fontFamily: "NotoSansTC-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 115.94,
        fill: "rgba(25,25,25,1)",
        align: "center",
        transform: [0.4, 0, 0, 0.4, 0, 0],
        lineNumber: 1,
        lineHeight: 0.68,
        letterSpacing: 2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 6,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_641",
        name: "CTA",
        x: 400,
        y: 1729,
        width: 279,
        height: 33,
        text: "SHOP NOW",
        fontFamily: "Lato-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 51.24,
        fill: "rgba(0,0,0,1)",
        align: "center",
        transform: [0.88, 0, 0, 0.88, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 5,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 7,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_642",
        name: "贴纸-用户专享",
        x: 340,
        y: 1797,
        width: 400,
        height: 35,
        text: "APP New Users Only",
        fontFamily: "WorkSans-Medium",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 37.62,
        fill: "rgba(0,0,0,1)",
        align: "center",
        transform: [0.98, 0, 0, 0.98, 0, 0],
        lineNumber: 1,
        lineHeight: 1.07,
        letterSpacing: 2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 8,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
    ],
  },
  {
    id: "9",
    image:
      "https://localhost:3001/images/image-0c5d16a5602d649a916ebb274a87d3e1.png",
    image_webp:
      "https://localhost:3001/images/image-0c5d16a5602d649a916ebb274a87d3e1.webp",
    width: 1080,
    height: 1920,
    colorMode: 3,
    layers: [
      {
        type: "image",
        id: "image_50",
        clipping: false,
        name: "背景1",
        y: 0,
        x: 0,
        width: 1080,
        height: 1920,
        image:
          "https://localhost:3001/images/image-4a9afd14d0c7a09de7ad426b13b07c13.png",
        image_webp:
          "https://localhost:3001/images/image-4a9afd14d0c7a09de7ad426b13b07c13.webp",
        zIndex: 0,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_22",
        clipping: false,
        name: "商品1-截图",
        y: -2,
        x: -6,
        width: 1092,
        height: 1456,
        image:
          "https://localhost:3001/images/image-8f4371dc12229b3245368e032c7964a5.png",
        image_webp:
          "https://localhost:3001/images/image-8f4371dc12229b3245368e032c7964a5.webp",
        zIndex: 1,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_5",
        clipping: false,
        name: "其他",
        y: 1391,
        x: 0,
        width: 1080,
        height: 530,
        image:
          "https://localhost:3001/images/image-07a26de7dd4472f44280d5fd9e4de49d.png",
        image_webp:
          "https://localhost:3001/images/image-07a26de7dd4472f44280d5fd9e4de49d.webp",
        zIndex: 2,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_7",
        name: "CTA",
        x: 105,
        y: 1696,
        width: 291,
        height: 35,
        text: "SHOP NOW",
        fontFamily: "Lato-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 36.77,
        fill: "rgba(0,0,0,1)",
        align: "center",
        transform: [1.27, 0, 0, 1.27, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 4,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 3,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_8",
        name: "文案1",
        x: 107,
        y: 1769,
        width: 865,
        height: 57,
        text: "SHOW OFF YOUR UNIQUE STYLE",
        fontFamily: "LilitaOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 61.24,
        fill: "rgba(139,107,70,1)",
        align: "left",
        transform: [1.02, 0, 0, 1.02, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 4,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_11",
        clipping: false,
        name: "贴纸-价格-其他",
        y: 1234,
        x: 569,
        width: 439,
        height: 439,
        image:
          "https://localhost:3001/images/image-98546aed86c708f4c577d386370a3c91.png",
        image_webp:
          "https://localhost:3001/images/image-98546aed86c708f4c577d386370a3c91.webp",
        zIndex: 5,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_13",
        name: "贴纸-价格-金额",
        x: 623,
        y: 1421,
        width: 334,
        height: 102,
        text: "$1.00",
        fontFamily: "TitanOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 119.13,
        fill: "rgba(255,185,0,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 6,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_14",
        name: "贴纸-价格-其他",
        x: 632,
        y: 1377,
        width: 213,
        height: 35,
        text: "Starting At",
        fontFamily: "TitanOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 36.21,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 7,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_15",
        clipping: false,
        name: "贴纸-免邮-其他",
        y: 1496,
        x: 105,
        width: 375,
        height: 98,
        image:
          "https://localhost:3001/images/image-71bf04cae8da5d14042e3bc07a635586.png",
        image_webp:
          "https://localhost:3001/images/image-71bf04cae8da5d14042e3bc07a635586.webp",
        zIndex: 8,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_16",
        name: "贴纸-免邮-文案",
        x: 142,
        y: 1530,
        width: 306,
        height: 30,
        text: "FREE SHIPPING",
        fontFamily: "TitanOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 40.19,
        fill: "rgba(255,185,0,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 9,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_18",
        clipping: false,
        name: "贴纸-用户专享",
        y: 1544,
        x: 771,
        width: 199,
        height: 199,
        image:
          "https://localhost:3001/images/image-e508c5fba4fdd684597fc321a143edfa.png",
        image_webp:
          "https://localhost:3001/images/image-e508c5fba4fdd684597fc321a143edfa.webp",
        zIndex: 10,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
    ],
  },
  {
    id: "1",
    image:
      "https://localhost:3001/images/image-60e448c26bd283d3eac48a2fa9b141d0.png",
    image_webp:
      "https://localhost:3001/images/image-60e448c26bd283d3eac48a2fa9b141d0.webp",
    width: 1200,
    height: 902,
    colorMode: 3,
    layers: [
      {
        type: "image",
        id: "image_15",
        clipping: false,
        name: "背景1",
        y: 0,
        x: 0,
        width: 1200,
        height: 902,
        image:
          "https://localhost:3001/images/image-4456a4d394e90dc881144ebce9cd5160.png",
        image_webp:
          "https://localhost:3001/images/image-4456a4d394e90dc881144ebce9cd5160.webp",
        zIndex: 0,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_4",
        clipping: false,
        name: "商品1-抠图",
        y: 64,
        x: 767,
        width: 260,
        height: 781,
        image:
          "https://localhost:3001/images/image-84a61ddab0fb0f70c55fb05e5563f786.png",
        image_webp:
          "https://localhost:3001/images/image-84a61ddab0fb0f70c55fb05e5563f786.webp",
        zIndex: 1,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_7",
        name: "CTA",
        x: 99,
        y: 543,
        width: 218,
        height: 25,
        text: "SHOP NOW",
        fontFamily: "Lato-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 35.11,
        fill: "rgba(0,0,0,1)",
        align: "center",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 4,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 2,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_8",
        name: "文案1",
        x: 102,
        y: 626,
        width: 508,
        height: 187,
        text: "UP TO\n90% OFF",
        fontFamily: "Coiny-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 110.56,
        fill: "rgba(61,104,126,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 2,
        lineHeight: 0.97,
        letterSpacing: 2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 3,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_14",
        name: "文案2",
        x: 137,
        y: 231,
        width: 538,
        height: 115,
        text: "SHOW OFF YOUR\nUNIQUE STYLE",
        fontFamily: "Coiny-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 59.63,
        fill: "rgba(61,104,126,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 2,
        lineHeight: 0.97,
        letterSpacing: 1,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 4,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_16",
        clipping: false,
        name: "贴纸-免邮-其他",
        y: 74,
        x: 98,
        width: 443,
        height: 57,
        image:
          "https://localhost:3001/images/image-a9b41256f9e73ddf21c509bb22d88da5.png",
        image_webp:
          "https://localhost:3001/images/image-a9b41256f9e73ddf21c509bb22d88da5.webp",
        zIndex: 5,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_17",
        name: "贴纸-免邮-文案",
        x: 139,
        y: 88,
        width: 359,
        height: 31,
        text: "FREE SHIPPING",
        fontFamily: "Coiny-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 43.44,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 0.97,
        letterSpacing: 1,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 6,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_18",
        name: "贴纸-用户专享",
        x: 99,
        y: 447,
        width: 398,
        height: 25,
        text: "APP NEW USERS ONLY",
        fontFamily: "WorkSans-Medium",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 37.17,
        fill: "rgba(61,104,126,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.08,
        letterSpacing: -1,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 7,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
    ],
  },
  {
    id: "7",
    image:
      "https://localhost:3001/images/image-b4d606324aa339a124382c4b9025d5d7.png",
    image_webp:
      "https://localhost:3001/images/image-b4d606324aa339a124382c4b9025d5d7.webp",
    width: 1200,
    height: 1200,
    colorMode: 3,
    layers: [
      {
        type: "image",
        id: "image_68",
        clipping: false,
        name: "背景1",
        y: 0,
        x: 0,
        width: 1200,
        height: 1200,
        image:
          "https://localhost:3001/images/image-b890f843a8e96810fcb562324012d6b5.png",
        image_webp:
          "https://localhost:3001/images/image-b890f843a8e96810fcb562324012d6b5.webp",
        zIndex: 0,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_37",
        clipping: false,
        name: "商品1-截图",
        y: 90,
        x: 445,
        width: 703,
        height: 943,
        image:
          "https://localhost:3001/images/image-8471f178c165381c90eff00b8d09705b.png",
        image_webp:
          "https://localhost:3001/images/image-8471f178c165381c90eff00b8d09705b.webp",
        zIndex: 1,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_7",
        clipping: false,
        name: "其他",
        y: 0,
        x: 0,
        width: 1200,
        height: 1200,
        image:
          "https://localhost:3001/images/image-06a0ff66e6b6a1411014a65ff780e521.png",
        image_webp:
          "https://localhost:3001/images/image-06a0ff66e6b6a1411014a65ff780e521.webp",
        zIndex: 2,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_9",
        clipping: false,
        name: "贴纸-免邮-其他",
        y: 48,
        x: 602,
        width: 388,
        height: 101,
        image:
          "https://localhost:3001/images/image-08968318f203938cf000bca28e647cd5.png",
        image_webp:
          "https://localhost:3001/images/image-08968318f203938cf000bca28e647cd5.webp",
        zIndex: 3,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_10",
        name: "贴纸-免邮-文案",
        x: 641,
        y: 82,
        width: 311,
        height: 31,
        text: "FREE SHIPPING",
        fontFamily: "TitanOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 40.69,
        fill: "rgba(255,255,255,1)",
        align: "right",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 4,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_11",
        name: "文案1",
        x: 73,
        y: 1098,
        width: 1063,
        height: 57,
        text: "SHOW OFF YOUR UNIQUE STYLE",
        fontFamily: "TitanOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 66.73,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.07,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 5,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_19",
        clipping: false,
        name: "其他",
        y: 868,
        x: 180,
        width: 138,
        height: 105,
        image:
          "https://localhost:3001/images/image-4825ed2d8f751c4af80d0f396f7cb1e0.png",
        image_webp:
          "https://localhost:3001/images/image-4825ed2d8f751c4af80d0f396f7cb1e0.webp",
        zIndex: 6,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_21",
        name: "贴纸-用户专享",
        x: 93,
        y: 88,
        width: 208,
        height: 70,
        text: "APP New\nUsers Only",
        fontFamily: "WorkSans-Medium",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 36.34,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 2,
        lineHeight: 1.09,
        letterSpacing: 2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 7,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_22",
        name: "CTA",
        x: 75,
        y: 1031,
        width: 314,
        height: 37,
        text: "SHOP NOW",
        fontFamily: "Lato-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 50.84,
        fill: "rgba(255,255,255,1)",
        align: "center",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 5,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 8,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_31",
        clipping: false,
        name: "贴纸-价格-其他",
        y: 247,
        x: 57,
        width: 470,
        height: 533,
        image:
          "https://localhost:3001/images/image-9f2d8c3315edb6774b15d73227e51b51.png",
        image_webp:
          "https://localhost:3001/images/image-9f2d8c3315edb6774b15d73227e51b51.webp",
        zIndex: 9,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_54",
        name: "贴纸-价格-金额",
        x: 103,
        y: 503,
        width: 355,
        height: 109,
        text: "$2.28",
        fontFamily: "WorkSans-Black",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 119.87,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1.1, 0, 0, 1.1, 0, 0],
        lineNumber: 1,
        lineHeight: 0.93,
        letterSpacing: -2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 10,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_55",
        name: "贴纸-价格-其他",
        x: 110,
        y: 448,
        width: 245,
        height: 45,
        text: "Starting at",
        fontFamily: "WorkSans-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 42.24,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1.1, 0, 0, 1.1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 11,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
    ],
  },
  {
    id: "3",
    image:
      "https://localhost:3001/images/image-5f98b87b010b1f511830c6b16635edc2.png",
    image_webp:
      "https://localhost:3001/images/image-5f98b87b010b1f511830c6b16635edc2.webp",
    width: 1200,
    height: 1500,
    colorMode: 3,
    layers: [
      {
        type: "image",
        id: "image_86",
        clipping: false,
        name: "背景1",
        y: 0,
        x: 0,
        width: 1200,
        height: 1500,
        image:
          "https://localhost:3001/images/image-73ee4684766a75c396149e1572c2ce27.png",
        image_webp:
          "https://localhost:3001/images/image-73ee4684766a75c396149e1572c2ce27.webp",
        zIndex: 0,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_41",
        clipping: false,
        name: "商品1-截图",
        y: 121,
        x: 401,
        width: 706,
        height: 948,
        image:
          "https://localhost:3001/images/image-96a63e3328ed254fd2ff34b8d15bbf2a.png",
        image_webp:
          "https://localhost:3001/images/image-96a63e3328ed254fd2ff34b8d15bbf2a.webp",
        zIndex: 1,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_7",
        clipping: false,
        name: "其他",
        y: 0,
        x: 0,
        width: 1200,
        height: 1500,
        image:
          "https://localhost:3001/images/image-30208214369c64b63d02939e66c933d6.png",
        image_webp:
          "https://localhost:3001/images/image-30208214369c64b63d02939e66c933d6.webp",
        zIndex: 2,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_9",
        clipping: false,
        name: "贴纸-免邮-其他",
        y: 90,
        x: 560,
        width: 388,
        height: 101,
        image:
          "https://localhost:3001/images/image-be6052901f8295120b7f48659db801fe.png",
        image_webp:
          "https://localhost:3001/images/image-be6052901f8295120b7f48659db801fe.webp",
        zIndex: 3,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_10",
        name: "贴纸-免邮-文案",
        x: 599,
        y: 124,
        width: 311,
        height: 31,
        text: "FREE SHIPPING",
        fontFamily: "TitanOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 40.69,
        fill: "rgba(255,255,255,1)",
        align: "right",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 4,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_11",
        name: "文案1",
        x: 83,
        y: 1220,
        width: 1036,
        height: 239,
        text: "SHOW OFF YOUR\nUNIQUE STYLE",
        fontFamily: "TitanOne-Regular",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 123.82,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 2,
        lineHeight: 1.07,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 5,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_19",
        clipping: false,
        name: "其他",
        y: 974,
        x: 980,
        width: 137,
        height: 105,
        image:
          "https://localhost:3001/images/image-ebe25697ef1d418ad5814756211af6f0.png",
        image_webp:
          "https://localhost:3001/images/image-ebe25697ef1d418ad5814756211af6f0.webp",
        zIndex: 6,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_21",
        name: "CTA",
        x: 90,
        y: 1130,
        width: 315,
        height: 37,
        text: "SHOP NOW",
        fontFamily: "Lato-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 50.91,
        fill: "rgba(255,255,255,1)",
        align: "center",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 5,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 7,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "image",
        id: "image_30",
        clipping: false,
        name: "贴纸-价格-其他",
        y: 90,
        x: 72,
        width: 445,
        height: 508,
        image:
          "https://localhost:3001/images/image-6fa8ec1cfb3180d35abe4813a2062e93.png",
        image_webp:
          "https://localhost:3001/images/image-6fa8ec1cfb3180d35abe4813a2062e93.webp",
        zIndex: 8,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_71",
        name: "贴纸-价格-金额",
        x: 131,
        y: 337,
        width: 323,
        height: 99,
        text: "$2.28",
        fontFamily: "WorkSans-Black",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 119.87,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 0.93,
        letterSpacing: -2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 9,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_70",
        name: "贴纸-价格-其他",
        x: 137,
        y: 277,
        width: 222,
        height: 41,
        text: "Starting at",
        fontFamily: "WorkSans-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 42.24,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 10,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_36",
        name: "贴纸-用户专享",
        x: 712,
        y: 1135,
        width: 395,
        height: 33,
        text: "APP New Users Only",
        fontFamily: "WorkSans-Medium",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 36.34,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.09,
        letterSpacing: 2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 11,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
    ],
  },
  {
    id: "6",
    image:
      "https://localhost:3001/images/image-aa99dfc017bf2d30f931a891030ccb17.png",
    image_webp:
      "https://localhost:3001/images/image-aa99dfc017bf2d30f931a891030ccb17.webp",
    width: 1200,
    height: 1500,
    colorMode: 3,
    layers: [
      {
        type: "image",
        id: "image_2",
        clipping: false,
        name: "背景1",
        y: -1,
        x: -1,
        width: 1202,
        height: 1501,
        image:
          "https://localhost:3001/images/image-de4096643dc047c4968a1f90eb945cbb.png",
        image_webp:
          "https://localhost:3001/images/image-de4096643dc047c4968a1f90eb945cbb.webp",
        zIndex: 0,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_4",
        clipping: false,
        name: "其他",
        y: 0,
        x: 0,
        width: 1200,
        height: 240,
        image:
          "https://localhost:3001/images/image-ba10285c6c5141a32cea0a08e1dfc1f7.png",
        image_webp:
          "https://localhost:3001/images/image-ba10285c6c5141a32cea0a08e1dfc1f7.webp",
        zIndex: 1,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_5",
        clipping: false,
        name: "商品1-抠图",
        y: 33,
        x: 239,
        width: 675,
        height: 1048,
        image:
          "https://localhost:3001/images/image-24e37e143555254f497afd08ea4a651d.png",
        image_webp:
          "https://localhost:3001/images/image-24e37e143555254f497afd08ea4a651d.webp",
        zIndex: 2,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_7",
        clipping: false,
        name: "其他",
        y: 888,
        x: 0,
        width: 1200,
        height: 616,
        image:
          "https://localhost:3001/images/image-80bb10a7a8ed100eae2b17f93ad7f9c3.png",
        image_webp:
          "https://localhost:3001/images/image-80bb10a7a8ed100eae2b17f93ad7f9c3.webp",
        zIndex: 3,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "image",
        id: "image_9",
        clipping: false,
        name: "贴纸-价格-其他",
        y: 714,
        x: 69,
        width: 415,
        height: 415,
        image:
          "https://localhost:3001/images/image-df9a9b85a0a7fcb7c1321ac462c17686.png",
        image_webp:
          "https://localhost:3001/images/image-df9a9b85a0a7fcb7c1321ac462c17686.webp",
        zIndex: 4,
        opacity: 1,
        fillOpacity: 1,
        visible: true,
        writable: true,
      },
      {
        type: "text",
        id: "text_11",
        name: "贴纸-价格-金额",
        x: 109,
        y: 858,
        width: 332,
        height: 124,
        text: "$1.00",
        fontFamily: "Lato-Black",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 127.71,
        fill: "rgba(255,255,255,1)",
        align: "left",
        transform: [1.03, 0, 0, 1.03, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 5,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_10",
        name: "贴纸-价格-其他",
        x: 187,
        y: 815,
        width: 184,
        height: 34,
        text: "Starting At",
        fontFamily: "Lato-Black",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 29.21,
        fill: "rgba(255,255,255,1)",
        align: "center",
        transform: [1.3, 0, 0, 1.3, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 0,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 6,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_52",
        name: "文案1",
        x: 179,
        y: 1171,
        width: 843,
        height: 195,
        text: "SHOW OFF YOUR\nUNIQUE STYLE",
        fontFamily: "WorkSans-BlackItalic",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 103.97,
        fill: "rgba(255,0,141,1)",
        align: "center",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 2,
        lineHeight: 0.99,
        letterSpacing: -2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 7,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_53",
        name: "贴纸-用户专享",
        x: 380,
        y: 1388,
        width: 438,
        height: 39,
        text: "APP New Users Only",
        fontFamily: "WorkSans-Medium",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 40.25,
        fill: "rgba(255,255,255,1)",
        align: "center",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.09,
        letterSpacing: 2,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 8,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_14",
        name: "CTA",
        x: 166,
        y: 1011,
        width: 226,
        height: 26,
        text: "SHOP NOW",
        fontFamily: "Lato-Bold",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 36.4,
        fill: "rgba(255,255,255,1)",
        align: "center",
        transform: [1, 0, 0, 1, 0, 0],
        lineNumber: 1,
        lineHeight: 1.2,
        letterSpacing: 4,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 9,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
      {
        type: "text",
        id: "text_55",
        name: "贴纸-免邮-文案",
        x: 77,
        y: 52,
        width: 413,
        height: 38,
        text: "FREE SHIPPING",
        fontFamily: "WorkSans-BlackItalic",
        fontStyle: "normal",
        strikethrough: false,
        underline: false,
        overline: false,
        fontWeight: "normal",
        fontSize: 58.22,
        fill: "rgba(255,0,141,1)",
        align: "center",
        transform: [0.95, 0, 0, 0.95, 0, 0],
        lineNumber: 1,
        lineHeight: 0.99,
        letterSpacing: -1,
        verticalScale: 1,
        horizontalScale: 1,
        visible: true,
        zIndex: 10,
        opacity: 1,
        fillOpacity: 1,
        writable: true,
        effectsOpen: false,
      },
    ],
  },
];
export { psdData };
